package org.loop.example

import dagger.Module
import android.location.LocationManager
import android.content.Context
import dagger.Provides
import javax.inject.Singleton

/**
 * Created by loop on 14/12/14.
 *
 * This class is unused but kept to show that annotated kotlin classes are not generated by Dagger2.
 */
//TODO remove this class
Module
public class UnusedAndroidModule(val application: BaseApplication) {

    Provides
    Singleton
    fun provideLocationManager(): LocationManager {
        return application.getSystemService(Context.LOCATION_SERVICE) as LocationManager
    }
}